---

- name: Configure AAP with SSL Management
  hosts: localhost
  vars:
    aap_config:
      # common options
      state: "present"
      organization: "Default"
      inventory: "Demo Inventory"
      project:
        name: "SSL"
        scm_url: "https://github.com/mrjoshuap/ansible_ssl.git"
        scm_branch: "main"
        scm_update_on_launch: true
      credentials:
        - "Demo Credential"
      controller_config_file: "./tower_cli.cfg"

      # state specific options
      create:
        playbook: "ssl_create.yml"

      deploy:
        playbook: "ssl_deploy.yml"
        destinations:
          - arista
          - cisco
          - citrix
          - f5
          - fortios
          - ibm-aix
          - ibm-mainframe-z
          - juniper
          - openshift
          - rhel-apache
          - rhel-java-keystore
          - rhel-nginx
          - windows-iis
          - windows-java-keystore

      query:
        playbook: "ssl_query.yml"
        sources:
          - letsencrypt
          - mscs
          - openssl
          - rhel-idm
          - venify
          - verisign
          - network-ports

      report:
        playbook: "ssl_report.yml"
        sources:
          - email
          - jira
          - servicenow
          - slack
          - teams

      sign:
        playbook: "ssl_sign.yml"
        sources:
          - letsencrypt
          - mscs
          - openssl
          - rhel-idm
          - venify
          - verisign

      validate:
        playbook: "ssl_validate.yml"

      verify:
        playbook: "ssl_verify.yml"

  tasks:

    - name: Create project for SSL Management
      ansible.controller.project:
        name: "{{ aap_config.project.name }}"
        organization: "{{ aap_config.organization }}"
        scm_type: git
        scm_url: "{{ aap_config.project.scm_url }}"
        scm_branch: "{{ aap_config.project.scm_branch }}"
        scm_update_on_launch: "{{ aap_config.project.scm_update_on_launch }}"
        state: "{{ aap_config.state }}"
        controller_config_file: "{{ aap_config.controller_config_file }}"

    ###
    # CREATE
    ###
    - name: Create Certificate Signing Requests
      ansible.controller.job_template:
        name: "SSL / Create"
        job_type: "run"
        organization: "{{ aap_config.organization }}"
        inventory: "{{ aap_config.inventory }}"
        project: "{{ aap_config.project.name }}"
        playbook: "{{ aap_config.create.playbook }}"
        credentials: "{{ aap_config.credentials }}"
        state: "{{ aap_config.state }}"
        controller_config_file: "{{ aap_config.controller_config_file }}"

    ###
    # DEPLOY
    ###
    - name: Deploy SSL Certificates
      ansible.controller.job_template:
        name: "SSL / Deploy / {{ item }}"
        job_type: "run"
        organization: "{{ aap_config.organization }}"
        inventory: "{{ aap_config.inventory }}"
        project: "{{ aap_config.project.name }}"
        playbook: "{{ aap_config.deploy.playbook }}"
        credentials: "{{ aap_config.credentials }}"
        state: "{{ aap_config.state }}"
        controller_config_file: "{{ aap_config.controller_config_file }}"
      loop: "{{ aap_config.deploy.destinations }}"

    ###
    # QUERY
    ###
    - name: Query SSL Certificates
      ansible.controller.job_template:
        name: "SSL / Query / {{ item }}"
        job_type: "run"
        organization: "{{ aap_config.organization }}"
        inventory: "{{ aap_config.inventory }}"
        project: "{{ aap_config.project.name }}"
        playbook: "{{ aap_config.query.playbook }}"
        credentials: "{{ aap_config.credentials }}"
        state: "{{ aap_config.state }}"
        controller_config_file: "{{ aap_config.controller_config_file }}"
      loop: "{{ aap_config.query.sources }}"

    ###
    # REPORT
    ###
    - name: Create SSL Certificate Reporting Job Templates
      ansible.controller.job_template:
        name: "SSL / Report / {{ item }}"
        job_type: "run"
        organization: "{{ aap_config.organization }}"
        inventory: "{{ aap_config.inventory }}"
        project: "{{ aap_config.project.name }}"
        playbook: "{{ aap_config.report.playbook }}"
        credentials: "{{ aap_config.credentials }}"
        state: "{{ aap_config.state }}"
        controller_config_file: "{{ aap_config.controller_config_file }}"
      loop: "{{ aap_config.report.sources }}"

    ###
    # SIGN
    ###
    - name: Sign SSL Certificates
      ansible.controller.job_template:
        name: "SSL / Sign / {{ item }}"
        job_type: "run"
        organization: "{{ aap_config.organization }}"
        inventory: "{{ aap_config.inventory }}"
        project: "{{ aap_config.project.name }}"
        playbook: "{{ aap_config.sign.playbook }}"
        credentials: "{{ aap_config.credentials }}"
        state: "{{ aap_config.state }}"
        controller_config_file: "{{ aap_config.controller_config_file }}"
      loop: "{{ aap_config.sign.sources }}"

    ###
    # VALIDATE
    ###
    - name: Validate SSL Certificates
      ansible.controller.job_template:
        name: "SSL / Validate"
        job_type: "run"
        organization: "{{ aap_config.organization }}"
        inventory: "{{ aap_config.inventory }}"
        project: "{{ aap_config.project.name }}"
        playbook: "{{ aap_config.validate.playbook }}"
        credentials: "{{ aap_config.credentials }}"
        state: "{{ aap_config.state }}"
        controller_config_file: "{{ aap_config.controller_config_file }}"

    ###
    # VERIFY
    ###
    - name: Verify SSL Certificates
      ansible.controller.job_template:
        name: "Verify SSL Certificate"
        job_type: "run"
        organization: "{{ aap_config.organization }}"
        inventory: "{{ aap_config.inventory }}"
        project: "{{ aap_config.project.name }}"
        playbook: "{{ aap_config.verify.playbook }}"
        credentials: "{{ aap_config.credentials }}"
        state: "{{ aap_config.state }}"
        controller_config_file: "{{ aap_config.controller_config_file }}"
