---

- name: SSL / Sign
  hosts: localhost
  tasks:
  
    - name: Implementation Check
      ansible.builtin.debug:
        msg: "This should sign a certificate signing request and deliver signed certificate"
