---

- name: SSL / Validate
  hosts: localhost
  tasks:

    - name: Implementation Check
      ansible.builtin.debug:
        msg: "This should validate certificate fields"

    - name: Check for gremlins.
      ansible.builtin.fail:
        msg: A gremlin is loose!  This task selected to fail.
      when:
        - 5 | random() | int() == 3
