---

- name: SSL / Verify
  hosts: localhost
  tasks:

    - name: Implementation Check
      ansible.builtin.debug:
        msg: "This should verify identified certificates expiration dates."

    - name: Check for gremlins.
      ansible.builtin.fail:
        msg: A gremlin is loose!  This task selected to fail.
      when:
        - 5 | random() | int() == 3
