---

- name: SSL / Create
  hosts: localhost
  tasks:

    - name: Implementation Check
      ansible.builtin.debug:
        msg: "This should create a new certificate signing request"

    - name: Check for gremlins.
      ansible.builtin.fail:
        msg: A gremlin is loose!  This task selected to fail.
      when:
        - 10 | random() | int() == 6
